apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (bc7d9f4f)
  labels:
    io.kompose.service: impalad
  name: impalad
spec:
  ports:
    - name: "21000"
      port: 21000
      targetPort: 21000
    - name: "21050"
      port: 21050
      targetPort: 21050
    - name: "25000"
      port: 25000
      targetPort: 25000
    - name: "28000"
      port: 28000
      targetPort: 28000
  selector:
    io.kompose.service: impalad
