apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (bc7d9f4f)
  labels:
    io.kompose.service: impalad
  name: impalad
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: impalad
  serviceName: impalad
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (bc7d9f4f)
      labels:
        io.kompose.network/quickstart-network: "true"
        io.kompose.service: impalad
    spec:
      containers:
        - args:
            - -v=1
            - -redirect_stdout_stderr=false
            - -logtostderr
            - -kudu_master_hosts=kudu-master-1:7051
            - -mt_dop_auto_fallback=true
            - -default_query_options=mt_dop=4,default_file_format=parquet,default_transactional_type=insert_only
            - -mem_limit=4gb
            - --enable_ldap_auth
            - --ldap_uri=ldap://openldap:1389
            - --ldap_bind_password_cmd=echo -n adminpassword
            - --ldap_passwords_in_clear_ok
            - --ldap_bind_dn=cn=admin,dc=c3,dc=ai
            - --ldap_bind_pattern=cn=#UID,ou=users,dc=c3,dc=ai
          env:
            - name: JAVA_TOOL_OPTIONS
              value: '"-Xmx1g"'
          image: apache/impala:81d5377c2-impalad_coord_exec
          name: impalad
          ports:
            - containerPort: 21000
            - containerPort: 21050
            - containerPort: 25000
            - containerPort: 28000
          resources: {}
          volumeMounts:
            - mountPath: /user/hive/warehouse
              name: impala-quickstart-warehouse
            - mountPath: /opt/impala/conf
              name: config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: impala-quickstart-warehouse
          persistentVolumeClaim:
            claimName: impala-quickstart-warehouse
        - name: config
          configMap:
            name: quickstart-config
            items:
            - key: "core-site.xml"
              path: "core-site.xml"
            - key: "hive-site.xml"
              path: "hive-site.xml"
