apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: impala-quickstart-warehouse
  name: impala-quickstart-warehouse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: '{{ .Values.fs.warehouse.storageClass }}'
  resources:
    requests:
      storage: {{ .Values.fs.warehouse.storageSize }}
