apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quickstart-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/quickstart-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/quickstart-network: "true"
