apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: impala-shell
    io.kompose.service: impala-shell
  name: impala-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: impala-shell
  serviceName: impala-shell
  template:
    metadata:
      labels:
        io.kompose.service: impala-shell
    spec:
      initContainers:
      # the main impala-shell container uses impala user; use root to 
      # initialized directories
      - name: adjust-data-dir-permissions
        image: alpine:3
        command:
        - chmod
        - a+rwx
        - /opt/impala/data
        volumeMounts:
        - name: data
          mountPath: /opt/impala/data
      containers:
        - image: {{ .Values.impalaShell.image }}
          name: impala-shell
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: '{{ .Values.impalaShell.azureStorageConnectionString }}'
            - name: ISSUER
              value: '{{ .Values.impalaShell.issuer }}'
            - name: CLIENT_ID
              value: '{{ .Values.impalaShell.clientId }}'
            - name: CLIENT_SECRET
              value: '{{ .Values.impalaShell.clientSecret }}'
            - name: AUTH_CALLBACK
              value: '{{ .Values.impalaShell.authCallback }}'
            - name: LO_REDIRECT_URL
              value: '{{ .Values.impalaShell.loRedirectUrl }}'
          command: 
          - /opt/impala/bin/wrapper.sh
          # - sleep
          args:
          # - infinity
          ports:
            - containerPort: 3000
            - containerPort: 3010
          resources:
            requests:
              cpu: "8000m"
              memory: "4Gi"
            limits:
              # spark shell will use 16 threads
              cpu: "16000m"
              memory: "16Gi"
          volumeMounts:
          - mountPath: /opt/impala/data
            name: data
          - mountPath: /opt/spark/conf
            name: spark-config
            readOnly: true
      volumes:
      - name: spark-config
        configMap:
          name: spark-config
          items:
          - key: "core-site.xml"
            path: "core-site.xml"
      restartPolicy: Always
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Ti
      volumeMode: Filesystem
