apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: impala-shell
  name: impala-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: impala-shell
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: impala-shell
    spec:
      containers:
        - image: {{ .Values.impalaShell.image }}
          name: impala-shell
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: '{{ .Values.impalaShell.azureStorageConnectionString }}'
          command: 
          - sleep
          args:
          - infinity
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "16Gi"
      restartPolicy: Always
