#!/bin/bash

/opt/spark/bin/spark-shell --executor-cores 80 --jars /opt/impala/spark/lib/azure-storage-7.0.0.jar,/opt/impala/spark/lib/azure-data-lake-store-sdk-2.2.9.jar,/opt/impala/spark/lib/hadoop-azure-3.2.2.jar,/opt/impala/spark/lib/jetty-util-ajax-9.4.20.v20190813.jar,/opt/impala/spark/lib/jetty-util-9.4.20.v20190813.jar "$@"
