fs:
  azure:
    accountKey: <azure account key>
  s3a:
    accessKey: <s3 access key>
    secretKey: <s3 secret key>
  warehouse:
    storageClass: azurefile-csi-nfs
    storageSize: 100Mi
impalad:
  image: apache/impala:81d5377c2-impalad_coord_exec
  javaToolOptions: '"-Xmx4g"'
impalaShell:
  image: c3ai/c3-impala-shell:1.24
catalogd:
  image: apache/impala:81d5377c2-catalogd
hms:
  image: c3ai/c3-impala-hms:1.0
statestored:
  image: apache/impala:81d5377c2-statestored
